//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: admin/v1/hubs_service.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HubsListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the first result. If not specified the default value will be zero.
	Offset *int32 `protobuf:"varint,1,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit         *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsListRequest) Reset() {
	*x = HubsListRequest{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsListRequest) ProtoMessage() {}

func (x *HubsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsListRequest.ProtoReflect.Descriptor instead.
func (*HubsListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{0}
}

func (x *HubsListRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *HubsListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type HubsListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or of the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size *int32 `protobuf:"varint,1,opt,name=size,proto3,oneof" json:"size,omitempty"`
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total *int32 `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// List of results.
	Items         []*Hub `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsListResponse) Reset() {
	*x = HubsListResponse{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsListResponse) ProtoMessage() {}

func (x *HubsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsListResponse.ProtoReflect.Descriptor instead.
func (*HubsListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{1}
}

func (x *HubsListResponse) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *HubsListResponse) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *HubsListResponse) GetItems() []*Hub {
	if x != nil {
		return x.Items
	}
	return nil
}

type HubsGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsGetRequest) Reset() {
	*x = HubsGetRequest{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsGetRequest) ProtoMessage() {}

func (x *HubsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsGetRequest.ProtoReflect.Descriptor instead.
func (*HubsGetRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{2}
}

func (x *HubsGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HubsGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Hub                   `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsGetResponse) Reset() {
	*x = HubsGetResponse{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsGetResponse) ProtoMessage() {}

func (x *HubsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsGetResponse.ProtoReflect.Descriptor instead.
func (*HubsGetResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{3}
}

func (x *HubsGetResponse) GetObject() *Hub {
	if x != nil {
		return x.Object
	}
	return nil
}

type HubsCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Hub                   `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsCreateRequest) Reset() {
	*x = HubsCreateRequest{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsCreateRequest) ProtoMessage() {}

func (x *HubsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsCreateRequest.ProtoReflect.Descriptor instead.
func (*HubsCreateRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{4}
}

func (x *HubsCreateRequest) GetObject() *Hub {
	if x != nil {
		return x.Object
	}
	return nil
}

type HubsCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Hub                   `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsCreateResponse) Reset() {
	*x = HubsCreateResponse{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsCreateResponse) ProtoMessage() {}

func (x *HubsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsCreateResponse.ProtoReflect.Descriptor instead.
func (*HubsCreateResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{5}
}

func (x *HubsCreateResponse) GetObject() *Hub {
	if x != nil {
		return x.Object
	}
	return nil
}

type HubsDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsDeleteRequest) Reset() {
	*x = HubsDeleteRequest{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsDeleteRequest) ProtoMessage() {}

func (x *HubsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsDeleteRequest.ProtoReflect.Descriptor instead.
func (*HubsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{6}
}

func (x *HubsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HubsDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsDeleteResponse) Reset() {
	*x = HubsDeleteResponse{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsDeleteResponse) ProtoMessage() {}

func (x *HubsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsDeleteResponse.ProtoReflect.Descriptor instead.
func (*HubsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{7}
}

type HubsUpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *HubStatus             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsUpdateStatusRequest) Reset() {
	*x = HubsUpdateStatusRequest{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsUpdateStatusRequest) ProtoMessage() {}

func (x *HubsUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*HubsUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{8}
}

func (x *HubsUpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HubsUpdateStatusRequest) GetStatus() *HubStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HubsUpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HubStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubsUpdateStatusResponse) Reset() {
	*x = HubsUpdateStatusResponse{}
	mi := &file_admin_v1_hubs_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubsUpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubsUpdateStatusResponse) ProtoMessage() {}

func (x *HubsUpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_hubs_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubsUpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*HubsUpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_hubs_service_proto_rawDescGZIP(), []int{9}
}

func (x *HubsUpdateStatusResponse) GetStatus() *HubStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_admin_v1_hubs_service_proto protoreflect.FileDescriptor

var file_admin_v1_hubs_service_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x75, 0x62, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76,
	0x31, 0x2f, 0x68, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5e, 0x0a, 0x0f, 0x48, 0x75, 0x62, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x7e, 0x0a, 0x10, 0x48, 0x75, 0x62, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x20, 0x0a, 0x0e, 0x48, 0x75, 0x62, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x38, 0x0a, 0x0f, 0x48, 0x75, 0x62, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x75, 0x62, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x3a, 0x0a, 0x11,
	0x48, 0x75, 0x62, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62,
	0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x3b, 0x0a, 0x12, 0x48, 0x75, 0x62, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x48, 0x75, 0x62, 0x73, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x48, 0x75,
	0x62, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x56, 0x0a, 0x17, 0x48, 0x75, 0x62, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x18, 0x48, 0x75, 0x62, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0xec, 0x02, 0x0a, 0x04, 0x48, 0x75, 0x62, 0x73, 0x12, 0x3f, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75,
	0x62, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75,
	0x62, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x75, 0x62, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0xa3, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x42, 0x10, 0x48, 0x75, 0x62, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x6e, 0x61, 0x62, 0x6f, 0x78, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x08,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_admin_v1_hubs_service_proto_rawDescOnce sync.Once
	file_admin_v1_hubs_service_proto_rawDescData []byte
)

func file_admin_v1_hubs_service_proto_rawDescGZIP() []byte {
	file_admin_v1_hubs_service_proto_rawDescOnce.Do(func() {
		file_admin_v1_hubs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_hubs_service_proto_rawDesc), len(file_admin_v1_hubs_service_proto_rawDesc)))
	})
	return file_admin_v1_hubs_service_proto_rawDescData
}

var file_admin_v1_hubs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_admin_v1_hubs_service_proto_goTypes = []any{
	(*HubsListRequest)(nil),          // 0: admin.v1.HubsListRequest
	(*HubsListResponse)(nil),         // 1: admin.v1.HubsListResponse
	(*HubsGetRequest)(nil),           // 2: admin.v1.HubsGetRequest
	(*HubsGetResponse)(nil),          // 3: admin.v1.HubsGetResponse
	(*HubsCreateRequest)(nil),        // 4: admin.v1.HubsCreateRequest
	(*HubsCreateResponse)(nil),       // 5: admin.v1.HubsCreateResponse
	(*HubsDeleteRequest)(nil),        // 6: admin.v1.HubsDeleteRequest
	(*HubsDeleteResponse)(nil),       // 7: admin.v1.HubsDeleteResponse
	(*HubsUpdateStatusRequest)(nil),  // 8: admin.v1.HubsUpdateStatusRequest
	(*HubsUpdateStatusResponse)(nil), // 9: admin.v1.HubsUpdateStatusResponse
	(*Hub)(nil),                      // 10: admin.v1.Hub
	(*HubStatus)(nil),                // 11: admin.v1.HubStatus
}
var file_admin_v1_hubs_service_proto_depIdxs = []int32{
	10, // 0: admin.v1.HubsListResponse.items:type_name -> admin.v1.Hub
	10, // 1: admin.v1.HubsGetResponse.object:type_name -> admin.v1.Hub
	10, // 2: admin.v1.HubsCreateRequest.object:type_name -> admin.v1.Hub
	10, // 3: admin.v1.HubsCreateResponse.object:type_name -> admin.v1.Hub
	11, // 4: admin.v1.HubsUpdateStatusRequest.status:type_name -> admin.v1.HubStatus
	11, // 5: admin.v1.HubsUpdateStatusResponse.status:type_name -> admin.v1.HubStatus
	0,  // 6: admin.v1.Hubs.List:input_type -> admin.v1.HubsListRequest
	2,  // 7: admin.v1.Hubs.Get:input_type -> admin.v1.HubsGetRequest
	4,  // 8: admin.v1.Hubs.Create:input_type -> admin.v1.HubsCreateRequest
	6,  // 9: admin.v1.Hubs.Delete:input_type -> admin.v1.HubsDeleteRequest
	8,  // 10: admin.v1.Hubs.UpdateStatus:input_type -> admin.v1.HubsUpdateStatusRequest
	1,  // 11: admin.v1.Hubs.List:output_type -> admin.v1.HubsListResponse
	3,  // 12: admin.v1.Hubs.Get:output_type -> admin.v1.HubsGetResponse
	5,  // 13: admin.v1.Hubs.Create:output_type -> admin.v1.HubsCreateResponse
	7,  // 14: admin.v1.Hubs.Delete:output_type -> admin.v1.HubsDeleteResponse
	9,  // 15: admin.v1.Hubs.UpdateStatus:output_type -> admin.v1.HubsUpdateStatusResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_v1_hubs_service_proto_init() }
func file_admin_v1_hubs_service_proto_init() {
	if File_admin_v1_hubs_service_proto != nil {
		return
	}
	file_admin_v1_hub_type_proto_init()
	file_admin_v1_hubs_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_v1_hubs_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_hubs_service_proto_rawDesc), len(file_admin_v1_hubs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_hubs_service_proto_goTypes,
		DependencyIndexes: file_admin_v1_hubs_service_proto_depIdxs,
		MessageInfos:      file_admin_v1_hubs_service_proto_msgTypes,
	}.Build()
	File_admin_v1_hubs_service_proto = out.File
	file_admin_v1_hubs_service_proto_goTypes = nil
	file_admin_v1_hubs_service_proto_depIdxs = nil
}
